### ISSUE TITLE
Menu icon invisible when dark menu theme applied

### ISSUE THREAD

**Issue by michaelwoods** [PuppyBongos/standing-desk-app#35]
OS X's dark menu theme hides the menu icon. It is visible when the menu bar is not active, adding a white/lighter icon would fix this issue.

![screen shot 2015-06-04 at 16 39 16 1](https://cloud.githubusercontent.com/assets/752976/8014301/9afb8392-0b9d-11e5-87ef-ad233805378b.png)
In this screenshot, the icon is to the left of the green bar.

**Comment by michaelchadwick** [comment]
This has been fixed in [0.9.1](https://github.com/PuppyBongos/standing-desk-app/releases/tag/0.9.1).
