### ISSUE TITLE
Request notification manual dismissal option

### ISSUE THREAD

**Issue by michaelwoods** [PuppyBongos/standing-desk-app#36]
Having a new standing desk and the ability to just walk away and come back easily, I find myself returning to the computer and having missed out on the notification that my state has changed to sitting.

Adding an option to require the dismissal of notifications would be great!

**Comment by michaelchadwick** [comment]
As far as I can tell, there is no way to keep the notification on the screen using Apple's built-in system (Growl may be a different story, but SDA is not currently set up to use it). You can always open up the notification center and see all of the notifications the app has delivered to see what you missed.

**Comment by radaly** [comment]
Hm but what about software update notifications. They definitely stick
there until you do something.

**Comment by michaelchadwick** [comment]
I researched this some more, and it looks like you can change all the notifications that SDA sends to "alert" style (stays on screen until dismissed) in code, but this can always be overridden by the user's system preference. If you need them to be alerts instead of banners (the default kind that disappears after a few seconds), then it's probably best to just turn that on in System Preferences.

**Comment by michaelwoods** [comment]
@michaelchadwick good enough for me, I didn't think to set that. Thanks!

**Comment by jameswald** [comment]
I had this same concern after a few missed notifications. Would you consider a contribution that adds a setting to toggle the notification / alert style even though it can always be overridden by System Preferences? On a related note, Alerts sometimes stack up if not dismissed:

![screen shot 2015-12-03 at 1 22 47 pm](https://cloud.githubusercontent.com/assets/875535/11577305/fa25178c-99c0-11e5-8d03-d2d7e40e6488.png)

Is it even possible for SDA to dismiss all but the most recent alert?

**Comment by michaelchadwick** [comment]
You mean adding a switch in the app between alerts and banners, that just reflects what is in System Preferences? Is that what most apps do? Not sure what the standard convention is nowadays.

**Comment by jameswald** [comment]
Yeah that's what I was thinking, but it looks like the default behavior with System Preferences is the way to go. Here's an example from Xcode:

![screen shot 2015-12-10 at 10 56 52 am](https://cloud.githubusercontent.com/assets/875535/11728247/e150e67a-9f2c-11e5-96e6-1cb1c1a3a9c7.png)
