### ISSUE TITLE
Specify a license

### ISSUE THREAD

**Issue by jameswald** [PuppyBongos/standing-desk-app#39]
It's helpful to specify the license that applies to this repository, otherwise GitHub's default licensing terms apply.

**Comment by michaelchadwick** [comment]
Excellent suggestion. Will add one soon.

**Comment by michaelchadwick** [comment]
MIT license added.

**Comment by jameswald** [comment]
Thanks and happy new year!

**Comment by michaelchadwick** [comment]
You, too!
