### ISSUE TITLE
Installed 1.0 but still getting warning about app from unidentified developer (signing?)

### ISSUE THREAD

**Issue by spovich** [PuppyBongos/standing-desk-app#40]
Installed on OS X 10.11 (El Capitan) and I get a warning about the app being from an unidentified developer. My security settings are for allowing apps from the App Store and Identified Developers.  I thought that signing the app meant you were an identified developer?

**Comment by michaelchadwick** [comment]
Confirmed this as an issue, and will look into it. Thanks!

**Comment by michaelchadwick** [comment]
By changing the DMG-style for releases to ZIP-style, this issue seems resolved. Not sure what happens when I put the DMG into DMG Canvas, but it seems to strip the signing of the app (or overrides its behavior or something). 1.0 and beyond will just be ZIPs for now.

**Comment by spovich** [comment]
@michaelchadwick Thanks!  I just downloaded and installed the zip and it worked nicely for me (no unsigned warning).  Thank you!
